driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
  - name: centos-5.10
  - name: debian-7.2.0
  - name: debian-6.0.8
  - name: freebsd-9.2
  - name: ubuntu-13.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04

suites:
  - name: default
    run_list: recipe[omnibus::default]
