---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
# - name: centos-5
#   driver:
#     image: centos:5

- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum -y install tar which initscripts

- name: centos-7
  driver:
    image: centos:7
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-21
  driver:
    image: fedora:21
    intermediate_instructions:
    - RUN yum clean all
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install tar

- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install apt-transport-https net-tools

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install apt-transport-https net-tools

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install apt-transport-https net-tools

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get -y install apt-transport-https net-tools

# - name: ubuntu-16.04
#   driver:
#     image: ubuntu:16.04
#     pid_one_command: /sbin/init
#     intermediate_instructions:
#       - RUN /usr/bin/apt-get update
#       - RUN /usr/bin/apt-get -y install apt-transport-https net-tools

suites:
  - name: default
    run_list: omnibus::default

  #
  # Build
  #
  - name: omnibus_build_execute
    run_list: omnibus_build::execute
